# Generated by Django 6.1 on 2026-09-13 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('business_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('ic_number', models.CharField(max_length=20)),
                ('student_type', models.CharField(choices=[('MONTHLY', 'Bulanan (Tetap)'), ('WALK_IN', 'Walk-in / Sambilan')], default='MONTHLY', max_length=20)),
                ('form_level', models.CharField(choices=[('S5', 'Darjah 5'), ('S6', 'Darjah 6'), ('F1', 'Form 1'), ('F2', 'Form 2'), ('F3', 'Form 3'), ('F4', 'Form 4'), ('F5', 'Form 5')], max_length=10)),
                ('stream', models.CharField(choices=[('SAINS', 'Aliran Sains'), ('SASTERA', 'Aliran Sastera'), ('GENERAL', 'Umum')], default='GENERAL', max_length=20)),
                ('school_name', models.CharField(blank=True, max_length=150)),
                ('school_code', models.CharField(blank=True, max_length=30)),
                ('school_category', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(max_length=30)),
                ('home_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('join_date', models.DateField()),
                ('lead_source', models.CharField(default='BANNER', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('ON_HOLD', 'Tangguh (On-Hold)'), ('TERMINATED', 'Berhenti / Tidak Aktif')], default='ACTIVE', max_length=20)),
                ('parent1_name', models.CharField(max_length=120)),
                ('parent1_phone', models.CharField(max_length=30)),
                ('parent1_email', models.EmailField(blank=True, max_length=254)),
                ('parent1_occupation', models.CharField(blank=True, max_length=100)),
                ('parent1_relation', models.CharField(default='Bapa', max_length=30)),
                ('parent2_name', models.CharField(blank=True, max_length=120)),
                ('parent2_phone', models.CharField(blank=True, max_length=30)),
                ('parent2_email', models.EmailField(blank=True, max_length=254)),
                ('parent2_occupation', models.CharField(blank=True, max_length=100)),
                ('parent2_relation', models.CharField(default='Ibu', max_length=30)),
                ('preferred_contact', models.CharField(choices=[('PARENT_1', 'Bapa/Penjaga 1'), ('PARENT_2', 'Ibu/Penjaga 2')], default='PARENT_1', max_length=20)),
                ('saps_consent', models.BooleanField(default=True)),
                ('agree_terms_7th_payment', models.BooleanField(default=True)),
                ('agree_terms_2months_auto_drop', models.BooleanField(default=True)),
                ('agree_terms_2weeks_notice', models.BooleanField(default=True)),
                ('checklist_ledger', models.BooleanField(default=False)),
                ('checklist_whatsapp', models.BooleanField(default=False)),
                ('checklist_senarai_pelajar', models.BooleanField(default=False)),
                ('checklist_kedatangan', models.BooleanField(default=False)),
                ('checklist_sistem_pembayaran', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_classes', models.ManyToManyField(blank=True, related_name='students', to='academic.classtimetable')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_config.subjectmaster')),
            ],
        ),
    ]
