# Generated by Django 6.1 on 2026-09-18 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=30, unique=True)),
                ('student_name', models.CharField(max_length=150)),
                ('parent_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('form_level', models.CharField(max_length=20)),
                ('school_name', models.CharField(blank=True, max_length=150)),
                ('lead_source', models.CharField(default='WHATSAPP', max_length=50)),
                ('interested_subjects', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ENQUIRY', 'Pertanyaan Awal (Enquiry)'), ('TRIAL', 'Percubaan Percuma (Free Trial)'), ('REGISTERED', 'Telah Daftar (Registered)'), ('LOST', 'Tidak Berminat (Lost)')], default='ENQUIRY', max_length=20)),
                ('trial_date', models.DateField(blank=True, null=True)),
                ('trial_feedback', models.TextField(blank=True)),
                ('assigned_to', models.CharField(default='Admin 1', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_origin', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
