# Generated by Django 6.1 on 2026-09-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='checklist_kedatangan',
        ),
        migrations.RemoveField(
            model_name='student',
            name='checklist_ledger',
        ),
        migrations.RemoveField(
            model_name='student',
            name='checklist_senarai_pelajar',
        ),
        migrations.RemoveField(
            model_name='student',
            name='checklist_sistem_pembayaran',
        ),
        migrations.RemoveField(
            model_name='student',
            name='checklist_whatsapp',
        ),
    ]
