# Generated by Django 6.1 on 2026-09-28 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_classtimetable_current_enrolled'),
        ('business_config', '0002_dynamicmasterdata'),
        ('students', '0003_remove_office_checklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentexamresult',
            options={'ordering': ['exam_date', 'id']},
        ),
        migrations.AddField(
            model_name='student',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='student',
            name='left_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='on_hold_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent1_age',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='parent2_age',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_decided_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='special_fee_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='special_monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='walk_in_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='walk_in_subjects',
            field=models.ManyToManyField(blank=True, related_name='walk_in_students', to='business_config.subjectmaster'),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='form_level',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Menunggu Kelulusan'), ('ACTIVE', 'Aktif'), ('ON_HOLD', 'Tangguh (On-Hold)'), ('TERMINATED', 'Berhenti / Tidak Aktif'), ('REJECTED', 'Pendaftaran Ditolak')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ClassAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('recorded_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timetable_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academic.classtimetable')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('timetable_class', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ClassWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Menunggu'), ('ENROLLED', 'Dimasukkan'), ('CANCELLED', 'Dibatalkan')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.CharField(blank=True, max_length=120)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='students.student')),
                ('timetable_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='academic.classtimetable')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REGISTERED', 'Didaftarkan'), ('APPROVED', 'Pendaftaran Diluluskan'), ('REJECTED', 'Pendaftaran Ditolak'), ('ADD_SUBJECT', 'Tambah Subjek'), ('DROP_SUBJECT', 'Gugur Subjek'), ('CHANGE_CLASS', 'Tukar Kelas'), ('WAITLIST', 'Senarai Menunggu'), ('ON_HOLD', 'Tangguh'), ('RESUME', 'Aktif Semula'), ('TERMINATE', 'Berhenti'), ('NOTE', 'Catatan')], max_length=20)),
                ('event_date', models.DateField()),
                ('class_label', models.CharField(blank=True, max_length=100)),
                ('reason_code', models.CharField(blank=True, max_length=60)),
                ('reason_text', models.TextField(blank=True)),
                ('hold_until', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('action', models.TextField(blank=True)),
                ('recorded_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academic.classtimetable')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='students.student')),
                ('timetable_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academic.classtimetable')),
            ],
            options={
                'ordering': ['-event_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.classattendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='students.student')),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
    ]
