# Generated by Django 6.1 on 2026-09-29 00:42

import datetime
import django.db.models.deletion

from datetime import timedelta
from django.db import migrations, models


def backfill_leads(apps, schema_editor):
    """Existing leads: dates from their timestamps, a first log entry, and a follow-up a week after the last update."""
    Lead = apps.get_model('students', 'Lead')
    LeadActivity = apps.get_model('students', 'LeadActivity')
    for lead in Lead.objects.all():
        lead.enquiry_date = lead.created_at.date()
        lead.stage_changed_at = lead.updated_at.date()
        if lead.status == 'REGISTERED' and lead.converted_student_id:
            Student = apps.get_model('students', 'Student')
            if Student.objects.filter(pk=lead.converted_student_id, status__in=('ACTIVE', 'ON_HOLD', 'TERMINATED')).exists():
                lead.status = 'ACTIVE'
        if lead.status == 'LOST':
            lead.lost_at_stage = 'ENQUIRY'  # the stage before loss was never recorded
        elif lead.status not in ('REGISTERED', 'ACTIVE'):
            lead.next_follow_up = lead.updated_at.date() + timedelta(days=7)
        lead.save(update_fields=['status', 'enquiry_date', 'stage_changed_at', 'lost_at_stage', 'next_follow_up'])
        LeadActivity.objects.create(
            lead=lead, activity_date=lead.enquiry_date, stage=lead.status, action='Lead baharu',
            remark=lead.notes, pic=lead.assigned_to or 'Sistem',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_backfill_registration_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='enquiry_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_at_stage',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_follow_up',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage_changed_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('CONTACTED', 'Contacted'), ('CONTENT_1', 'Content 1'), ('CONTENT_2', 'Content 2'), ('TRIAL', 'Free Trial'), ('WAITING_PAYMENT', 'Waiting Payment'), ('REGISTERED', 'Registered'), ('ACTIVE', 'Active'), ('LOST', 'Tidak Berminat (Lost)')], default='ENQUIRY', max_length=20),
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(default=datetime.date.today)),
                ('stage', models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('CONTACTED', 'Contacted'), ('CONTENT_1', 'Content 1'), ('CONTENT_2', 'Content 2'), ('TRIAL', 'Free Trial'), ('WAITING_PAYMENT', 'Waiting Payment'), ('REGISTERED', 'Registered'), ('ACTIVE', 'Active'), ('LOST', 'Tidak Berminat (Lost)')], max_length=20)),
                ('from_stage', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True)),
                ('pic', models.CharField(max_length=100)),
                ('outcome', models.CharField(choices=[('DONE', 'Selesai'), ('WAITING_REPLY', 'Menunggu Respons'), ('NO_RESPONSE', 'Tiada Respons')], default='DONE', max_length=20)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='students.lead')),
            ],
            options={
                'ordering': ['-activity_date', '-id'],
            },
        ),
        migrations.RunPython(backfill_leads, migrations.RunPython.noop),
    ]
