# Generated by Django 6.1 on 2026-09-29 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_monthly_invoicing_discounts'),
        ('students', '0006_lead_funnel_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='standing_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='billing.discount'),
        ),
    ]
