# Generated by Django 6.1 on 2026-09-29 15:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_monthly_invoicing_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentevent',
            name='event_type',
            field=models.CharField(choices=[('REGISTERED', 'Didaftarkan'), ('APPROVED', 'Pendaftaran Diluluskan'), ('REJECTED', 'Pendaftaran Ditolak'), ('ADD_SUBJECT', 'Tambah Subjek'), ('DROP_SUBJECT', 'Gugur Subjek'), ('CHANGE_CLASS', 'Tukar Kelas'), ('WAITLIST', 'Senarai Menunggu'), ('ON_HOLD', 'Tangguh'), ('RESUME', 'Aktif Semula'), ('TERMINATE', 'Berhenti'), ('NOTE', 'Catatan'), ('FEEDBACK', 'Maklum Balas')], max_length=20),
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('given_by', models.CharField(choices=[('PARENT', 'Ibu bapa'), ('STUDENT', 'Pelajar')], default='PARENT', max_length=10)),
                ('description', models.TextField()),
                ('recorded_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='students.student')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
