# Generated by Django 6.1 on 2026-09-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_uploads_and_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='form_level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentevent',
            name='event_type',
            field=models.CharField(choices=[('REGISTERED', 'Didaftarkan'), ('APPROVED', 'Pendaftaran Diluluskan'), ('REJECTED', 'Pendaftaran Ditolak'), ('ADD_SUBJECT', 'Tambah Subjek'), ('DROP_SUBJECT', 'Gugur Subjek'), ('CHANGE_CLASS', 'Tukar Kelas'), ('WAITLIST', 'Senarai Menunggu'), ('ON_HOLD', 'Tangguh'), ('RESUME', 'Aktif Semula'), ('TERMINATE', 'Berhenti'), ('NOTE', 'Catatan'), ('PROMOTE', 'Naik Tingkatan'), ('FEEDBACK', 'Maklum Balas')], max_length=20),
        ),
    ]
