# Generated by Django 6.1 on 2026-10-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_configurable_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='late',
            field=models.BooleanField(default=False),
        ),
    ]
