# Generated by Django 6.1 on 2026-09-13 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('billing_month', models.DateField()),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=240.0, max_digits=8)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('discount_remarks', models.CharField(blank=True, max_length=150)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('UNPAID', 'Belum Bayar'), ('PARTIAL', 'Sebahagian'), ('PAID', 'Selesai Bayar'), ('OVERDUE', 'Tertunggak')], default='UNPAID', max_length=20)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=40, unique=True)),
                ('payment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(choices=[('DUITNOW_QR', 'DuitNow QR'), ('ONLINE_BANKING', 'Online Banking / FPX'), ('CASH', 'Tunai'), ('CARD', 'Kad Debit/Kredit')], default='DUITNOW_QR', max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('received_by', models.CharField(default='Admin Pejabat', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student')),
            ],
        ),
    ]
