# Generated by Django 6.1 on 2026-09-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='overpaid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='payment_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='payment_type',
            field=models.CharField(choices=[('REG_FEE', 'Yuran Pendaftaran'), ('MONTHLY', 'Yuran Bulanan'), ('SEMINAR', 'Seminar'), ('OUTSTANDING', 'Tunggakan')], default='MONTHLY', max_length=20),
        ),
    ]
