# Generated by Django 6.1 on 2026-09-29 00:58

import django.db.models.deletion
from django.db import migrations, models


def backfill_invoice_type(apps, schema_editor):
    Invoice = apps.get_model('billing', 'Invoice')
    Invoice.objects.filter(registration_fee=0).update(invoice_type='MONTHLY')


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_phase2_history_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('mode', models.CharField(choices=[('FIXED', 'RM'), ('PERCENT', '%')], default='FIXED', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recurring', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='credit_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('FIRST', 'Pendaftaran & Bulan Pertama'), ('MONTHLY', 'Yuran Bulanan'), ('OTHER', 'Lain-lain (Seminar dll.)')], default='FIRST', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.discount'),
        ),
        migrations.RunPython(backfill_invoice_type, migrations.RunPython.noop),
    ]
