# Generated by Django 6.1 on 2026-09-13 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_code', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('teacher_type', models.CharField(choices=[('PERMANENT', 'Cikgu Permanent'), ('REPLACEMENT', 'Cikgu Ganti Aktif')], default='PERMANENT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('teaching_permit_expiry', models.DateField(blank=True, null=True)),
                ('rate_per_session', models.DecimalField(decimal_places=2, default=60.0, max_digits=8)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('subjects_qualified', models.ManyToManyField(blank=True, to='business_config.subjectmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Hadir'), ('ABSENT', 'Tidak Hadir'), ('REPLACED', 'Diganti')], default='PRESENT', max_length=20)),
                ('allowance_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('remarks', models.TextField(blank=True)),
                ('replacement_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements_done', to='teachers.teacher')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='teachers.teacher')),
            ],
        ),
    ]
