# Generated by Django 6.1 on 2026-09-18 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=100)),
                ('department', models.CharField(default='Pentadbiran & Khidmat Pelanggan', max_length=100)),
                ('ic_number', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('al_balance', models.IntegerField(default=11)),
                ('mc_balance', models.IntegerField(default=12)),
                ('el_balance', models.IntegerField(default=2)),
                ('ul_balance', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in', models.CharField(default='08:30 AM', max_length=20)),
                ('clock_out', models.CharField(blank=True, max_length=20, null=True)),
                ('total_hours', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(default='Pusat Tuisyen An Nur (Telipot, KB)', max_length=150)),
                ('status', models.CharField(default='PRESENT', max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='teachers.staffmember')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_id', models.CharField(max_length=30, unique=True)),
                ('leave_type', models.CharField(choices=[('AL', 'Cuti Tahunan (AL)'), ('MC', 'Cuti Sakit (MC)'), ('EL', 'Cuti Kecemasan (EL)'), ('UL', 'Cuti Tanpa Gaji (UL)')], default='AL', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_count', models.IntegerField(default=1)),
                ('reason', models.TextField()),
                ('mc_document', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Kelulusan'), ('APPROVED', 'Diluluskan'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=20)),
                ('supervisor_remark', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='teachers.staffmember')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
