# Generated by Django 6.1 on 2026-09-28 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_staffmember_staffattendance_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField()),
                ('complained_by', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Rendah'), ('MEDIUM', 'Sederhana'), ('HIGH', 'Tinggi')], default='LOW', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Baru'), ('IN_PROGRESS', 'Dalam Tindakan'), ('RESOLVED', 'Selesai')], default='OPEN', max_length=20)),
                ('action_taken', models.TextField(blank=True)),
                ('action_pic', models.CharField(blank=True, max_length=120)),
                ('action_date', models.DateField(blank=True, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-date_reported', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherRateIncrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('proposed_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Kelulusan'), ('APPROVED', 'Diluluskan'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=20)),
                ('proposed_by', models.CharField(blank=True, max_length=120)),
                ('decided_by', models.CharField(blank=True, max_length=120)),
                ('decision_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_increments', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
            },
        ),
    ]
