# Generated by Django 6.1 on 2026-09-29 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_classtimetable_current_enrolled'),
        ('teachers', '0003_teachercomplaint_teacherrateincrement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjustment_note', models.CharField(blank=True, max_length=200)),
                ('amount_payable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draf (dikira)'), ('VERIFIED', 'Disahkan Supervisor'), ('APPROVED', 'Diluluskan Management'), ('REJECTED', 'Ditolak Management'), ('PAID', 'Telah Dibayar')], default='DRAFT', max_length=20)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=120)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.CharField(blank=True, max_length=120)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('BANK_TRANSFER', 'Pindahan Bank'), ('CASH', 'Tunai'), ('CHEQUE', 'Cek')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('paid_by', models.CharField(blank=True, max_length=120)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-month', 'teacher__full_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='teacherattendance',
            options={'ordering': ['-date', 'class_label']},
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='class_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='recorded_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='timetable_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_attendances', to='academic.classtimetable'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Hadir'), ('ABSENT', 'Tidak Hadir'), ('REPLACED', 'Diganti'), ('CANCELLED', 'Kelas Batal')], default='PRESENT', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='teacherattendance',
            constraint=models.UniqueConstraint(fields=('timetable_class', 'date'), name='one_record_per_class_per_day'),
        ),
        migrations.AddField(
            model_name='teacherpayment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='teachers.teacher'),
        ),
        migrations.AddConstraint(
            model_name='teacherpayment',
            constraint=models.UniqueConstraint(fields=('teacher', 'month'), name='one_payment_per_teacher_month'),
        ),
    ]
