# Generated by Django 6.1 on 2026-09-29 14:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_staff_times_and_entitlements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('change', models.TextField()),
                ('remark', models.TextField(blank=True)),
                ('recorded_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('target', models.CharField(max_length=200)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('achieved', models.CharField(blank=True, max_length=200)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SET', 'Ditetapkan'), ('REVIEWED', 'Disemak')], default='SET', max_length=10)),
                ('set_by', models.CharField(blank=True, max_length=120)),
                ('reviewed_by', models.CharField(blank=True, max_length=120)),
                ('review_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', 'staff__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StaffRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('remark', models.TextField(blank=True)),
                ('recorded_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='corrected_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='dependents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='emergency_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='emergency_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='emergency_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='employment_type',
            field=models.CharField(choices=[('PERMANENT', 'Tetap'), ('CONTRACT', 'Kontrak'), ('PART_TIME', 'Sambilan'), ('INTERN', 'Pelatih / Latihan Industri')], default='PERMANENT', max_length=20),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Bujang'), ('MARRIED', 'Berkahwin'), ('DIVORCED', 'Bercerai'), ('WIDOWED', 'Balu / Duda')], max_length=10),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='work_days',
            field=models.CharField(default='0,1,2,3,4,5', max_length=20),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='work_end',
            field=models.TimeField(default=datetime.time(17, 30)),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='work_start',
            field=models.TimeField(default=datetime.time(8, 30)),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.UniqueConstraint(fields=('staff', 'date'), name='one_attendance_per_staff_day'),
        ),
        migrations.AddField(
            model_name='staffhistory',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='teachers.staffmember'),
        ),
        migrations.AddField(
            model_name='staffkpi',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='teachers.staffmember'),
        ),
        migrations.AddField(
            model_name='staffrecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='teachers.staffmember'),
        ),
    ]
