# Generated by Django 6.1 on 2026-10-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_staff_hr_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teaching_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
