# Generated by Django 6.1 on 2026-10-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_teacher_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_type',
            field=models.CharField(choices=[('PERMANENT', 'Cikgu Permanent'), ('REPLACEMENT', 'Sambilan (Part-time)')], default='PERMANENT', max_length=20),
        ),
    ]
