# Generated by Django 6.1 on 2026-09-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_category', models.CharField(choices=[('SECONDARY', 'Sekolah Menengah (Form 1 - 5)'), ('DARJAH_5', 'Darjah 5'), ('DARJAH_6', 'Darjah 6'), ('WALK_IN', 'Walk-in Rate')], max_length=20)),
                ('subject_count', models.IntegerField(default=4)),
                ('price_per_subject', models.DecimalField(decimal_places=2, default=60.0, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, default=240.0, max_digits=8)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['level_category', 'subject_count'],
            },
        ),
        migrations.CreateModel(
            name='SubjectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('level_category', models.CharField(choices=[('PRIMARY', 'Primary (Darjah 5-6)'), ('LOWER_SEC', 'Lower Secondary (Form 1-3)'), ('UPPER_SEC', 'Upper Secondary (Form 4-5)')], max_length=20)),
                ('stream', models.CharField(choices=[('TERAS', 'Teras / General'), ('SAINS', 'Aliran Sains'), ('SASTERA', 'Aliran Sastera')], default='TERAS', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_type', models.CharField(max_length=30, unique=True)),
                ('base_rate_per_session', models.DecimalField(decimal_places=2, default=60.0, max_digits=8)),
                ('annual_increment_pct', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
