# Generated by Django 6.1 on 2026-09-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicMasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('code', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=150)),
                ('meta_info', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Kelulusan (Pending)'), ('APPROVED', 'Diluluskan & Aktif (Approved)'), ('REJECTED', 'Ditolak (Rejected)')], db_index=True, default='APPROVED', max_length=20)),
                ('created_by', models.CharField(default='Admin 1', max_length=100)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'code'],
                'unique_together': {('category', 'code')},
            },
        ),
    ]
