# Generated by Django 6.1 on 2026-09-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_config', '0002_dynamicmasterdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmasterdata',
            name='proposal_note',
            field=models.TextField(blank=True),
        ),
    ]
