# Generated by Django 6.1 on 2026-10-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_config', '0004_grade_next_and_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingtier',
            name='group_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='level_category',
            field=models.CharField(max_length=40),
        ),
    ]
