# Generated by Django 6.1 on 2026-09-13 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=30, unique=True)),
                ('vendor_name', models.CharField(max_length=150)),
                ('pic_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('tin_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv_number', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(default='ONLINE_TRANSFER', max_length=50)),
                ('ref_number', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items_description', models.TextField()),
                ('remarks', models.TextField(blank=True)),
                ('tier_level', models.CharField(choices=[('TIER_1', 'Below RM500 (Admin Verification)'), ('TIER_2', 'RM500 - RM3,000 (Supervisor Approval)'), ('TIER_3', 'Above RM3,000 (Management Approval)')], default='TIER_1', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draf'), ('VERIFIED_ADMIN', 'Disahkan Admin'), ('APPROVED_SUPERVISOR', 'Diluluskan Supervisor'), ('APPROVED_MANAGEMENT', 'Diluluskan Pengurusan'), ('REJECTED', 'Ditolak')], default='DRAFT', max_length=30)),
                ('prepared_by', models.CharField(default='Admin', max_length=100)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.vendor')),
            ],
        ),
    ]
