# Generated by Django 6.1 on 2026-09-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='approval_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draf'), ('VERIFIED_ADMIN', 'Disahkan Admin'), ('PENDING_SUPERVISOR', 'Menunggu Kelulusan Supervisor'), ('PENDING_MANAGEMENT', 'Menunggu Kelulusan Pengurusan'), ('APPROVED_SUPERVISOR', 'Diluluskan Supervisor'), ('APPROVED_MANAGEMENT', 'Diluluskan Pengurusan'), ('REJECTED', 'Ditolak')], default='DRAFT', max_length=30),
        ),
    ]
