# Generated by Django 6.1 on 2026-10-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_voucher_approval_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='tier_level',
            field=models.CharField(choices=[('TIER_1', 'Tier 1: Admin verification'), ('TIER_2', 'Tier 2: Supervisor approval'), ('TIER_3', 'Tier 3: Management approval')], default='TIER_1', max_length=20),
        ),
    ]
