# Generated by Django 6.1 on 2026-09-13 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_config', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('JUMAAT', 'Jumaat'), ('SABTU', 'Sabtu'), ('ISNIN', 'Isnin'), ('SELASA', 'Selasa'), ('RABU', 'Rabu'), ('KHAMIS', 'Khamis')], max_length=15)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('period_label', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_level', models.CharField(choices=[('S5', 'Darjah 5'), ('S6', 'Darjah 6'), ('F1', 'Form 1'), ('F2', 'Form 2'), ('F3', 'Form 3'), ('F4', 'Form 4'), ('F5', 'Form 5')], max_length=10)),
                ('section', models.CharField(choices=[('A', 'Seksyen A'), ('B', 'Seksyen B'), ('C', 'Seksyen C'), ('D', 'Seksyen D')], default='A', max_length=5)),
                ('max_seats', models.IntegerField(default=20)),
                ('current_enrolled', models.IntegerField(default=0)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_config.subjectmaster')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.timeslot')),
            ],
            options={
                'ordering': ['form_level', 'subject', 'section'],
            },
        ),
        migrations.CreateModel(
            name='ClassRescheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_label', models.CharField(max_length=20)),
                ('tarikh_batal', models.DateField(blank=True, null=True)),
                ('tarikh_ganti', models.DateField(blank=True, null=True)),
                ('is_extra_class', models.BooleanField(default=False)),
                ('reason_type', models.CharField(choices=[('PH', 'Cuti Umum / Hari Pelepasan Am'), ('MARKING_PAPER', 'Guru Menanda Kertas Peperiksaan'), ('TIME_MISTAKE', 'Pembetulan Jadual / Masa Bertindih'), ('EMERGENCY_LEAVE', 'Kecemasan / Cuti Sakit Guru'), ('EXTRA_SESSION', 'Kelas Tambahan Peperiksaan'), ('OTHER', 'Lain-lain')], default='OTHER', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('supervisor_approved', models.BooleanField(default=False)),
                ('whatsapp_notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timetable_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='academic.classtimetable')),
            ],
        ),
    ]
