# Generated by Django 6.1 on 2026-09-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonHandout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handout_id', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('form_level', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=100)),
                ('class_code', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=120)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('file_name', models.CharField(default='Modul_Latihan_AnNur_2026.pdf', max_length=200)),
                ('file_size', models.CharField(default='2.5 MB', max_length=50)),
                ('file_type', models.CharField(default='PDF Document', max_length=50)),
                ('copies_needed', models.IntegerField(default=20)),
                ('copies_printed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PRINT_READY', 'Sedia Dicetak'), ('NEEDS_PRINTING', 'Perlu Dicetak'), ('ARCHIVED', 'Arkib')], default='PRINT_READY', max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
