# Generated by Django 6.1 on 2026-09-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_lessonhandout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtimetable',
            name='current_enrolled',
        ),
    ]
