# Generated by Django 6.1 on 2026-09-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_classtimetable_current_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonhandout',
            name='file_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lessonhandout',
            name='file_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lessonhandout',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
