# Generated by Django 6.1 on 2026-09-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_handout_file_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtimetable',
            name='form_level',
            field=models.CharField(max_length=10),
        ),
    ]
