# Generated by Django 6.1 on 2026-09-30 11:57

import django.db.models.deletion
from django.db import migrations, models


def backfill_status(apps, schema_editor):
    ClassRescheduleLog = apps.get_model('academic', 'ClassRescheduleLog')
    ClassRescheduleLog.objects.filter(supervisor_approved=True).update(status='APPROVED')


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_configurable_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='classreschedulelog',
            name='decided_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='classreschedulelog',
            name='decision_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classreschedulelog',
            name='recorded_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='classreschedulelog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Menunggu Kelulusan Supervisor'), ('APPROVED', 'Diluluskan'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='classreschedulelog',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classreschedulelog',
            name='verified_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='TimetableChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Tambah Kelas'), ('UPDATE', 'Ubah Kelas'), ('DELETE', 'Padam Kelas')], max_length=10)),
                ('class_label', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Kelulusan Management'), ('APPROVED', 'Diluluskan'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=10)),
                ('requested_by', models.CharField(blank=True, max_length=120)),
                ('decided_by', models.CharField(blank=True, max_length=120)),
                ('decision_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('timetable_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='academic.classtimetable')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_status, migrations.RunPython.noop),
    ]
