# Generated by Django 6.1 on 2026-10-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_timetable_approvals'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.CharField(choices=[('JUMAAT', 'Jumaat'), ('SABTU', 'Sabtu'), ('AHAD', 'Ahad'), ('ISNIN', 'Isnin'), ('SELASA', 'Selasa'), ('RABU', 'Rabu'), ('KHAMIS', 'Khamis')], max_length=15),
        ),
    ]
