# Generated by Django 6.1 on 2026-09-29 15:20

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('STUDENT_PHOTO', 'Gambar Pelajar'), ('FEEDBACK', 'Maklum Balas (gambar/video)'), ('STAFF_PHOTO', 'Gambar Staf'), ('STAFF_DOC', 'Dokumen Sokongan Staf'), ('VOUCHER', 'Lampiran Baucar'), ('VOUCHER_SIGNATURE', 'Tandatangan Penerima'), ('HANDOUT', 'Fail Nota / Modul')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=core.models.attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('doc_type', models.CharField(blank=True, choices=[('IC', 'Salinan Kad Pengenalan'), ('RESUME', 'Resume'), ('OFFER_LETTER', 'Surat Tawaran'), ('OTHER', 'Lain-lain')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_by_name', models.CharField(blank=True, max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
                'indexes': [models.Index(fields=['kind', 'object_id'], name='core_attach_kind_079387_idx')],
            },
        ),
    ]
