# Generated by Django 6.1 on 2026-10-05 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_uploads_and_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SUBJECT', 'Subjek')], max_length=20)),
                ('action', models.CharField(choices=[('CREATE', 'Tambah'), ('UPDATE', 'Ubah')], max_length=10)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu kelulusan'), ('APPROVED', 'Diluluskan'), ('REJECTED', 'Ditolak'), ('WITHDRAWN', 'Ditarik balik')], default='PENDING', max_length=10)),
                ('direct', models.BooleanField(default=False)),
                ('requested_by_name', models.CharField(max_length=150)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.CharField(blank=True, max_length=150)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True)),
                ('seen', models.BooleanField(default=False)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
    ]
