# Generated by Django 6.1 on 2026-10-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_change_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='kind',
            field=models.CharField(choices=[('SUBJECT', 'Subjek'), ('VENDOR', 'Pembekal')], max_length=20),
        ),
    ]
