# Generated by Django 6.1 on 2026-10-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_change_request_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='kind',
            field=models.CharField(choices=[('SUBJECT', 'Subjek'), ('VENDOR', 'Pembekal'), ('EXPENSE_CATEGORY', 'Kategori perbelanjaan'), ('EXPENSE_SUBCATEGORY', 'Subkategori perbelanjaan')], max_length=20),
        ),
    ]
