# Generated by Django 6.1 on 2026-10-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_change_request_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='kind',
            field=models.CharField(choices=[('SUBJECT', 'Subjek'), ('VENDOR', 'Pembekal'), ('EXPENSE_CATEGORY', 'Kategori perbelanjaan'), ('EXPENSE_SUBCATEGORY', 'Subkategori perbelanjaan'), ('TEACHER', 'Guru')], max_length=20),
        ),
    ]
