# Generated by Django 6.1 on 2026-10-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teacher_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Tambah'), ('UPDATE', 'Ubah'), ('DELETE', 'Padam')], max_length=10),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='kind',
            field=models.CharField(choices=[('SUBJECT', 'Subjek'), ('VENDOR', 'Pembekal'), ('EXPENSE_CATEGORY', 'Kategori perbelanjaan'), ('EXPENSE_SUBCATEGORY', 'Subkategori perbelanjaan'), ('TEACHER', 'Guru'), ('PRICING_TIER', 'Pakej yuran'), ('DISCOUNT', 'Diskaun')], max_length=20),
        ),
    ]
