# Generated by Django 6.1 on 2026-10-06 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_change_request_fees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('CREATED', 'Akaun dibuat'), ('ROLE_CHANGED', 'Peranan diubah'), ('DEACTIVATED', 'Dinyahaktifkan'), ('REACTIVATED', 'Diaktifkan semula'), ('PASSWORD_RESET', 'Kata laluan ditetapkan semula'), ('PASSWORD_CHANGED', 'Kata laluan ditukar'), ('RENAMED', 'Nama diubah'), ('LINKED', 'Pautan staf diubah')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=250)),
                ('by_name', models.CharField(blank=True, max_length=150)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
