# Generated by Django 6.1 on 2026-10-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='kind',
            field=models.CharField(choices=[('SUBJECT', 'Subjek'), ('VENDOR', 'Pembekal'), ('EXPENSE_CATEGORY', 'Kategori perbelanjaan'), ('EXPENSE_SUBCATEGORY', 'Subkategori perbelanjaan'), ('TEACHER', 'Guru'), ('PRICING_TIER', 'Pakej yuran'), ('DISCOUNT', 'Diskaun'), ('TIME_SLOT', 'Slot masa'), ('CLASSROOM', 'Bilik darjah'), ('CLOSED_DATE', 'Tarikh tutup')], max_length=20),
        ),
    ]
