# Generated by Django 6.1 on 2026-10-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=60)),
                ('old_value', models.CharField(blank=True, max_length=300)),
                ('new_value', models.CharField(blank=True, max_length=300)),
                ('by_name', models.CharField(blank=True, max_length=150)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
    ]
